COSTALEROS = [
  { "id": 1, "nombre": "Aitor Guirao Rodriguez",            "altura": 151, "pref_hombro": "" },
  { "id": 2, "nombre": "Cristo Fernando Abadía Lóp",        "altura": 149, "pref_hombro": "" },
  { "id": 3, "nombre": "Miguel Ángel Amorós Rodríg",        "altura": 149, "pref_hombro": "" },
  { "id": 4, "nombre": "Beatriz Jara Rodriguez",            "altura": 147, "pref_hombro": "" },
  { "id": 5, "nombre": "Natalia Belmonte Bas",              "altura": 146, "pref_hombro": "" },
  { "id": 6, "nombre": "Milagros Peñalver Lorenzo",         "altura": 146, "pref_hombro": "" },
  { "id": 7, "nombre": "Pablo Martínez Pérez",              "altura": 139, "pref_hombro": "" },
  { "id": 8, "nombre": "M Rosa García Cabrera",             "altura": 140, "pref_hombro": "" },
  { "id": 9, "nombre": "M Dolores Rodriguez Lorente",       "altura": 144, "pref_hombro": "" },
  { "id": 10, "nombre": "Cinthia Bernabé Donate",           "altura": 144, "pref_hombro": "" },
  { "id": 11, "nombre": "Álvaro Sarmiento Caselles",        "altura": 145, "pref_hombro": "" },
  { "id": 12, "nombre": "Moises Lorente Irles",             "altura": 146, "pref_hombro": "" },
  { "id": 13, "nombre": "David Lorca Rodríguez",            "altura": 154, "pref_hombro": "" },
  { "id": 14, "nombre": "Iván Fenoll Rodriguez",            "altura": 152, "pref_hombro": "" },
  { "id": 15, "nombre": "Oscar Martinez Mora",              "altura": 150, "pref_hombro": "" },
  { "id": 16, "nombre": "Ramón Escobedo Pérez",             "altura": 149, "pref_hombro": "" },
  { "id": 17, "nombre": "Abraham Sarmiento Marín",          "altura": 149, "pref_hombro": "" },
  { "id": 18, "nombre": "Daniel Mira Juan",                 "altura": 147, "pref_hombro": "" },
  { "id": 19, "nombre": "Jose Antonio Lidón Pérez",         "altura": 155, "pref_hombro": "" },
  { "id": 20, "nombre": "Nuria Ortega Lidón",               "altura": 151, "pref_hombro": "" },
  { "id": 21, "nombre": "Antonio Jesús Cabrera Ferránd",    "altura": 150, "pref_hombro": "" },
  { "id": 22, "nombre": "Miguel Angel Espinosa Mula",       "altura": 149, "pref_hombro": "" },
  { "id": 23, "nombre": "Raúl Donate Escudero",             "altura": 148, "pref_hombro": "" },
  { "id": 24, "nombre": "Cristina Rubio Blanco",            "altura": 139, "pref_hombro": "" },
  { "id": 25, "nombre": "Ana M Rodríguez Lorente",          "altura": 140, "pref_hombro": "" },
  { "id": 26, "nombre": "Pilar de Lourdes Martínez P",      "altura": 142, "pref_hombro": "" },
  { "id": 27, "nombre": "Carmen M Hernández Cáma",          "altura": 143, "pref_hombro": "" },
  { "id": 28, "nombre": "Mariano Diaz Vélez",               "altura": 144, "pref_hombro": "" },
  { "id": 29, "nombre": "Cristina Sánchez Moya",            "altura": 145, "pref_hombro": "" },
  { "id": 30, "nombre": "Zenaida Carmen Vivancos Vivar",    "altura": 140, "pref_hombro": "" },
  { "id": 31, "nombre": "Antonio Lidón Martínez",           "altura": 140, "pref_hombro": "" },
  { "id": 32, "nombre": "Ana Isabel Martínez Javaloyes",    "altura": 143, "pref_hombro": "" },
  { "id": 33, "nombre": "Monserrate Coll Mula",             "altura": 144, "pref_hombro": "" },
  { "id": 34, "nombre": "M Jesús Tovar Cuenca",             "altura": 144, "pref_hombro": "" },
  { "id": 35, "nombre": "Gelen Huertas Mateo",              "altura": 146, "pref_hombro": "" },
  { "id": 36, "nombre": "Jose Ramón Escobedo Med",          "altura": 139, "pref_hombro": "" },
  { "id": 37, "nombre": "Carla Fernández Ballesta",         "altura": 138, "pref_hombro": "" },
  { "id": 38, "nombre": "Alicia Murcia Ros",                "altura": 137, "pref_hombro": "" },
  { "id": 39, "nombre": "M Adela Ros Marín",                "altura": 136, "pref_hombro": "" },
  { "id": 40, "nombre": "Blanca Rosa Medina Oltra",         "altura": 136, "pref_hombro": "" },
  { "id": 41, "nombre": "Paula Marco Ruíz",                 "altura": 136, "pref_hombro": "" },
  { "id": 42, "nombre": "M José Sánchez Fernández",         "altura": 128, "pref_hombro": "" },
  { "id": 43, "nombre": "Erika Navarro Zaragoza",           "altura": 129, "pref_hombro": "" },
  { "id": 44, "nombre": "Nuria Laguía Martínez",            "altura": 131, "pref_hombro": "" },
  { "id": 45, "nombre": "Carmen Bas Martí",                 "altura": 132, "pref_hombro": "" },
  { "id": 46, "nombre": "M Pilar Cerezo Palop",             "altura": 133, "pref_hombro": "" },
  { "id": 47, "nombre": "M Dolores Zárate Chumillas",       "altura": 134, "pref_hombro": "" }
]